from pathlib import Path
import json,base64
root=Path(__file__).resolve().parents[1]
rows=json.loads((root/'results/viewer_series.json').read_text())
specs={p.name.replace('_graph.json',''):json.loads(p.read_text()) for p in (root/'inputs').glob('*_graph.json')}
imgs={s:base64.b64encode((root/'figures'/('graph_'+s+'.png')).read_bytes()).decode() for s in specs}
payload=json.dumps(dict(series=rows,specs=specs,images=imgs),ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')
html=r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Six-case topology simulation explorer</title>
<style>
:root{font-family:system-ui,Arial,sans-serif;color:#1a2b35;background:#edf2f5;font-size:16px}*{box-sizing:border-box}body{margin:0}header{background:#163343;color:white;padding:24px max(18px,calc((100vw - 1200px)/2))}header h1{font-size:clamp(1.4rem,3vw,2.1rem);margin:0 0 8px}header p{max-width:1000px;margin:0;line-height:1.5}main{max-width:1230px;margin:auto;padding:18px}.notice,.card{background:white;border:1px solid #ced9df;border-radius:10px;padding:16px;margin-bottom:16px}.notice{border-left:5px solid #a56b21;line-height:1.5}.controls{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}label{font-weight:650;font-size:.91rem}select,input[type=number]{display:block;width:100%;font:inherit;padding:9px;border:1px solid #a4b5be;border-radius:6px;margin-top:5px;background:white}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.stat{background:#f0f5f8;padding:12px;border-radius:8px}.stat b{display:block;font-size:1.55rem;margin-top:5px}small{font-size:.8rem}.muted{font-size:.91rem;line-height:1.5}canvas{display:block;width:100%;height:310px}h2{font-size:1.2rem;margin:0 0 10px}h3{font-size:1rem}.toolbar{display:flex;align-items:center;gap:12px;flex-wrap:wrap}button{font:inherit;padding:9px 14px;background:#173b50;color:white;border:0;border-radius:6px;cursor:pointer}input[type=range]{flex:1;min-width:150px}img{max-width:100%;height:auto}.legend{font-size:.84rem;display:flex;gap:15px;flex-wrap:wrap;margin:10px 0}details summary{cursor:pointer;font-weight:700}.readme{line-height:1.65}code{background:#eef1f3;padding:2px 4px}footer{font-size:.85rem;padding:10px 0 20px} @media(max-width:720px){.controls{grid-template-columns:repeat(2,1fr)}.stats{grid-template-columns:repeat(2,1fr)}canvas{height:280px}main{padding:10px}}@media(max-width:420px){.controls{grid-template-columns:1fr}}
</style></head><body><header><h1>Six-case hydro-topological simulation explorer</h1><p>Recorded source-routing results + live finite-buffer stress test. CDO and five Southeast Asian analogues. Fully offline.</p></header><main>
<div class="notice"><strong>Model boundary:</strong> These are report-derived <strong>coarse network models</strong> with synthetic inputs and parameters, not mapped flood forecasts. A tick is not an hour; spill is not flood depth. CDO is not a demonstrated Lapasan inundation node. The six PDFs do not contain complete georeferenced drainage networks.</div>
<section class="card"><h2>1. Choose a recorded source-routing case</h2><div class="controls">
<label>Network<select id="site"></select></label><label>Observation point<select id="role"><option value="receiver">Downstream receiving probe</option><option value="urban">Urban / corridor probe</option></select></label>
<label>Source pulse duration<select id="duration"><option>2</option><option selected>8</option><option>24</option></select></label>
<label>Pulse shape<select id="shape"><option value="block">Constant block</option><option value="triangle">Triangular</option></select></label>
<label>Starting-time spread<select id="spread"><option>0</option><option selected>8</option><option>24</option></select></label>
<label>Named storage release parameter<select id="tau"><option>0</option></select></label></div>
<p class="muted">This demonstration subset uses equal source weights, all source groups active, unit logical-link delays, zero ordinary link memory and realization 0. The full 1,152-scenario grammar, area sensitivity, graph alternatives and counterexamples are in the reproducibility package.</p>
<div id="caseinfo" class="muted"></div></section>
<section class="card"><h2>2. Change the hypothetical receiving capacity and buffer</h2><div class="controls"><label>Service capacity (units/tick)<input type="number" id="capacity" min="0" max="100" step="0.5" value="5"></label><label>Available buffer (units)<input type="number" id="buffer" min="0" max="1000" step="5" value="10"></label><label>Source curves<select id="sourceview"><option value="none">Combined input only</option><option value="all">Combined + individual source contributions</option></select></label></div><p class="muted">Each observation is a standalone experiment: spills at different probes must not be added together. Positive capacity is given enough extra ticks to drain the remaining buffer. A closed outlet retains water rather than deleting it.</p><div class="stats" id="stats"></div><p id="audit" class="muted"></p></section>
<section class="card"><h2 id="plotTitle">3. See arrivals and buffer overflow</h2><div class="toolbar"><button id="play">Play marker</button><input type="range" id="tick" min="0" max="100" value="0"><span id="tickLabel">Tick 0</span><button id="export">Export selected series CSV</button></div>
<h3>Incoming contributions at the selected point (units per tick)</h3><canvas id="arrivals"></canvas><div class="legend" id="legend"></div>
<h3>Stored units and spilled units in each tick</h3><canvas id="inventory"></canvas><p class="muted">Solid line: stored amount. Vertical bars: spill during that tick. Dashed horizontal line: available buffer. The marker is a timeline guide, not a moving flood front on a map.</p></section>
<section class="card"><details open><summary>4. Source-constrained coarse graph and evidence limit</summary><img id="graph" alt="Explicit coarse source-routing graph"><p id="provenance" class="muted"></p><p id="limits" class="muted"></p></details></section>
<section class="card readme"><h2>How to interpret the experiment</h2><p><strong>Structure determines which routes contributions share.</strong> Pulse timing and routing functions determine when they meet. A capacity/buffer threshold determines whether this defined model spills. Similar topology does not guarantee identical output when those parameters differ.</p><p><strong>Three useful comparisons:</strong> change source starting-time spread while keeping capacity and buffer fixed; compare neutral and active storage in Manado/Huong; compare the Huong urban point with its downstream receiver to see why Bo is not added before Hue.</p><p><strong>Do not turn these values into real annual flood probabilities.</strong> No measured storm frequency, channel capacity, water level, local drain geometry or Lapasan flood footprint was fitted. The larger experiment contains negative findings and counterexamples as well as positive mean effects.</p></section><footer>Source keys and graph definitions are in the accompanying methods/results report. This viewer uses source-tagged routed series generated by the bundled Python model; its live buffer update uses the same equations.</footer></main>
<script id="dataset" type="application/json">__DATA__</script><script>__CORE__</script><script>
const DATA=JSON.parse(document.getElementById('dataset').textContent),$=x=>document.getElementById(x);
let current=null,result=null,timer=null,displayLength=100;
const controls=['role','duration','shape','spread','tau','capacity','buffer','sourceview'];
for(const [key,sp] of Object.entries(DATA.specs)){let o=document.createElement('option');o.value=key;o.textContent=sp.label;$('site').append(o)}$('site').value='CDO';
function syncTau(){const site=$('site').value,old=$('tau').value;const vals=[...new Set(DATA.series.filter(s=>s.case===site).map(s=>s.tau))].sort((a,b)=>a-b);$('tau').replaceChildren();for(const v of vals){let o=document.createElement('option');o.value=v;o.textContent=v===0?'0 — neutral':v+' — synthetic memory';$('tau').append(o)}$('tau').value=vals.includes(Number(old))?old:'0'}
function stop(){if(timer)clearInterval(timer);timer=null;$('play').textContent='Play marker'}
function update(){stop();const site=$('site').value,sp=DATA.specs[site];current=DATA.series.find(s=>s.case===site&&s.role===$('role').value&&s.tau===Number($('tau').value)&&s.scenario.duration===Number($('duration').value)&&s.scenario.shape===$('shape').value&&s.scenario.spread===Number($('spread').value));if(!current)throw new Error('No recorded scenario matches controls');
let cap=Number($('capacity').value),buf=Number($('buffer').value);if(!Number.isFinite(cap)||cap<0)cap=0;if(!Number.isFinite(buf)||buf<0)buf=0;cap=Math.min(100,cap);buf=Math.min(1000,buf);if(cap>0&&cap<.1)cap=.1;$('capacity').value=cap;$('buffer').value=buf;
const n=current.tagged[0].length,q=Array(n).fill(0);for(const a of current.tagged)for(let t=0;t<n;t++)q[t]+=a[t];result=queueModel(q,cap,buf);let last=0;for(let t=0;t<result.q.length;t++)if(result.q[t]>1e-7||result.spill[t]>1e-7||result.out[t]>1e-7)last=t;displayLength=Math.max(35,Math.min(result.q.length,last+10));if(cap===0)displayLength=Math.max(35,n);
const entries=[['Input received',result.received.toFixed(2)],['Spilled units',result.spillTotal.toFixed(2)],['Spill / basin input',(result.spillTotal).toFixed(2)+'%'],['Released units',result.delivered.toFixed(2)],['Still stored',result.remaining.toFixed(2)]];$('stats').replaceChildren();for(const [label,value] of entries){const c=document.createElement('div');c.className='stat';const sm=document.createElement('small');sm.textContent=label;const b=document.createElement('b');b.textContent=value;c.append(sm,b);$('stats').append(c)}
$('audit').textContent='Water-accounting error: '+result.error.toExponential(2)+' units. Total source event = 100 units. A probe may receive less when some sources join farther downstream.';
$('caseinfo').textContent='Scenario '+current.scenario.scenario_id+' | Node '+current.node+': '+sp.names[current.node]+' | Source starts: '+current.names.map((x,i)=>x+' @ '+current.starts[i]).join('; ');
$('graph').src='data:image/png;base64,'+DATA.images[site];$('provenance').textContent=sp.provenance;$('limits').textContent=sp.limitations;
$('tick').max=displayLength-1;$('tick').value=0;redraw()}
function setup(canvas){const dpr=window.devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const c=canvas.getContext('2d');c.scale(dpr,dpr);return {c,w,h}}
function base(canvas,max,title){const {c,w,h}=setup(canvas),pad={l:58,r:20,t:24,b:38};const X=t=>pad.l+(w-pad.l-pad.r)*t/(displayLength-1),Y=v=>h-pad.b-(h-pad.t-pad.b)*v/max;
c.font='12px system-ui';c.beginPath();c.moveTo(pad.l,pad.t);c.lineTo(pad.l,h-pad.b);c.lineTo(w-pad.r,h-pad.b);c.stroke();for(let k=0;k<5;k++){const y=k*max/4;c.fillText(y.toFixed(1),4,Y(y)+4)}for(let k=0;k<6;k++){const t=Math.round(k*(displayLength-1)/5);c.fillText(String(t),X(t)-7,h-12)}c.fillText(title,pad.l,13);return {c,X,Y,w,h,pad}}
function line(z,arr,dash=[],width=1){const {c,X,Y}=z;c.setLineDash(dash);c.lineWidth=width;c.beginPath();for(let t=0;t<displayLength;t++){const x=X(t),y=Y(arr[t]||0);t?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();c.setLineDash([]);c.lineWidth=1}
function redraw(){if(!result)return;const cap=Math.max(0,Math.min(100,Number($('capacity').value)||0)),buf=Math.max(0,Math.min(1000,Number($('buffer').value)||0)),tick=Number($('tick').value);$('tickLabel').textContent='Tick '+tick;
let max=Math.max(1,...result.q.slice(0,displayLength),cap)*1.15,z=base($('arrivals'),max,'Input units / tick');line(z,result.q,[],2.5);line(z,Array(displayLength).fill(cap),[8,5],1);
$('legend').textContent='Solid thick: combined input. Dashed: assigned service capacity.';if($('sourceview').value==='all'){current.tagged.forEach((a,i)=>line(z,a,[i+1,3],1));$('legend').textContent+=' Source order: '+current.names.join(' | ')}
for(const graph of [z]){graph.c.globalAlpha=.35;line(graph,[],[],1);graph.c.beginPath();graph.c.moveTo(graph.X(tick),graph.pad.t);graph.c.lineTo(graph.X(tick),graph.h-graph.pad.b);graph.c.stroke();graph.c.globalAlpha=1}
max=Math.max(1,...result.stock.slice(0,displayLength),...result.spill.slice(0,displayLength),buf)*1.15;z=base($('inventory'),max,'Stored units / spilled units per tick');for(let t=0;t<displayLength;t++){z.c.globalAlpha=.22;z.c.fillRect(z.X(t)-2,z.Y(result.spill[t]||0),4,z.Y(0)-z.Y(result.spill[t]||0))}z.c.globalAlpha=1;line(z,result.stock,[],2);line(z,Array(displayLength).fill(buf),[8,5]);z.c.globalAlpha=.35;z.c.beginPath();z.c.moveTo(z.X(tick),z.pad.t);z.c.lineTo(z.X(tick),z.h-z.pad.b);z.c.stroke();z.c.globalAlpha=1}
$('site').addEventListener('change',()=>{syncTau();update()});for(const id of controls)$(id).addEventListener('change',update);$('tick').addEventListener('input',redraw);window.addEventListener('resize',redraw);
$('play').onclick=()=>{if(timer){stop();return}if(Number($('tick').value)>=displayLength-1)$('tick').value=0;$('play').textContent='Pause';timer=setInterval(()=>{let t=Number($('tick').value)+1;if(t>=displayLength){stop();return}$('tick').value=t;redraw()},90)};
$('export').onclick=()=>{let text='tick,arriving,released,spilled,stored\n';for(let t=0;t<result.q.length;t++)text+=[t,result.q[t],result.out[t],result.spill[t],result.stock[t]].join(',')+'\n';const url=URL.createObjectURL(new Blob([text],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=current.case+'_scenario_'+current.scenario.scenario_id+'_probe_'+current.node+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
syncTau();update();
</script></body></html>'''
html=html.replace('__DATA__',payload).replace('__CORE__',(root/'code/viewer_core.js').read_text())
p=root.parent/'SEA_Topology_Simulation_Explorer.html';p.write_text(html,encoding='utf-8')
print(p,len(html),'characters')
